### ISSUE TITLE
Bot is down (dev: i can't find free hosting)

### ISSUE THREAD

**Issue by BlurryLabyrinth** [KruASe76/Codenames-bot#1]
I added your bot to my server this morning.  I have tried all the commands but it keeps coming back the the application did not respond.

**Comment by KruASe76** [comment]
Oh, i should have noted this somewhere long time ago...
The bot is indeed down. Since it is a pet-project and i'm just a student, i really don't want to pay for a hosting. And since Oracle has left Russia and Belarus without service two years ago, i have been searching the internet for a replacement to their "always free" instance, however didn't find anything that suited technical requirements and could store just a small SQLite database :(
So the bot is down for 13 months already and i can't even localhost it because i have my laptop with me almost always so it doesn't have persistent internet connection.

Sorry for inconvenience. I will make a note in the README. And if you know totally free hosting (that also doesn't require adding a payment method, as fly.io does, for example), please give a link.

Also there are hosting instruction in the README, if anyone wants to self-host. However in that case there would not be access to the global statistics database.

**Comment by KruASe76** [comment]
Bot is up and running!

My old laptop is a hosting now :D

**Comment by BlurryLabyrinth** [comment]
OK.  I added the bot to my server but when we start the game and confirm the game it does not start.  Do I need to open a new ticket for this?

**Comment by KruASe76** [comment]
as i see from logs, the bot has not a permission to send messages in the text channel. if you've added the bot to your server long ago (more than a year?), since then required permission could've changed so please try to re-invite the bot using the badge with link in the README.
